resources:
- alias: accelerometerData
  format: string
- alias: accelerometerError
  format: string
- alias: accelerometerReady
  format: string
- alias: ambientError
  format: string
- alias: ambientLight
  format: string
- alias: ambientLightTrigger
  format: string
- alias: ambientReady
  format: string
- alias: ambientSound
  format: string
- alias: ambientSoundTrigger
  format: string
- alias: climateHumidity
  format: string
- alias: climateReady
  format: string
- alias: climateTemperature
  format: string
- alias: infraredData
  format: string
- alias: infraredError
  format: string
- alias: infraredReady
  format: string
- alias: relayError
  format: string
- alias: relayLatch
  format: string
- alias: relayReady
  format: string
- alias: rfidData
  format: string
- alias: rfidError
  format: string
- alias: rfidRead
  format: string
- alias: rfidReady
  format: string
- alias: servoError
  format: string
- alias: servoReady
  format: string
